SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Player
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

# Shot
SHOT_RADIUS = 1
SHOT_VELOCITY = 1
MAX_SHOT_VELOCITY = 400
SHOT_DELAY = 60
SHOT_ACCELERATION = 1.05
SHOT_SIZE_INCREASE = 0.2
MAX_SHOT_RADIUS = 15
